### ISSUE TITLE
Small Suggestion

### ISSUE THREAD

**Issue by Lucidi0us** [andrewstellman/excel-check-printing#1]
Changing the content of B12 to the following will add a line of dashes after the amount in text to provide more security.  I arbitrarily picked 75 dashes, I am sure there is an exact minimum that would work.

=CONCATENATE(SpellNumber(F32),"  ---------------------------------------------------------------------------")

**Comment by andrewstellman** [comment]
That's a great suggestion. Thanks!

To make it a little more flexible, I did this:
-  added cell F36 with value "FALSE" and the label in F35 _"Add horizontal line after amount:"_  – set this to TRUE to turn on the horizontal line
-  set the formula of B12 to this: `=IF(F36,CONCATENATE(SpellNumber(F32),"   ",REPT("–",1000)),SpellNumber(F32))` – it uses the em-dash character (–) to make an unbroken line, and the REPT function repeat it (it's cut off by the DOLLARS text in L12, so I used a large value)
