### ISSUE TITLE
name?

### ISSUE THREAD

**Issue by mavennumber1** [andrewstellman/excel-check-printing#3]

**Comment by mavennumber1** [comment]
on B12 instead of the amount it came on name

**Comment by andrewstellman** [comment]
B12 spells whatever number is in cell F32. Maybe the name was entered into F32 instead of the amount?

**Comment by mavennumber1** [comment]
first of all andrewstellman1  Thanks for the amazing sheet,
I Entered 950 in F32, and I see in L 9-10 also the same amount, But in B12 I see #name? there is some error 
maybe I have a different version of excel i have 2013

**Comment by andrewstellman** [comment]
Ah, okay. `#NAME` is what Excel displays in a cell when it can't find a function. You'll get this if you try to load the file in Excel but disable macros. If you choose enable macros when you load, it should work.
