### ISSUE TITLE
missing info when trying to print check

### ISSUE THREAD

**Issue by kaywhy101** [andrewstellman/excel-check-printing#5]
the print section isn't large enough to cover all the check info--the dollar amount is always left out of the page. any way to fix this? 

![image](https://user-images.githubusercontent.com/109816206/180481641-b6a7c2f6-8ff8-4501-9988-d8428acc7568.png)

**Comment by andrewstellman** [comment]
Sure! It looks like maybe the right margin is really big—try setting it to .5". If that doesn't work, everything on that sheet is done with column widths and row heights, so the easiest way to adjust it is to unlock the sheet, then drag and adjust the column widths until everything shows up in the print preview.
