### ISSUE TITLE
Could you edit this to fit personal sized check?

### ISSUE THREAD

**Issue by duhd1993** [andrewstellman/excel-check-printing#6]
Like this one https://www.amazon.com/Three-Personal-Sized-Blank-Check/dp/B002WCVW5Q or https://www.amazon.com/VersaCheck-Secure-Checks-Business-31BP01-01255-4/dp/B0106CBE3S/
BTW, is there a standard for the format or you just manually adjusted it to about right?

**Comment by andrewstellman** [comment]
I manually adjusted it. There are some standards with check printing, like the ratio format for the routing number (which I included in the template). But technically you can write a check on anything, in any format, and the bank is supposed to accept it. I read a story once about someone writing a check on the back of a label they peeled off of a wine bottle, although I don't know if the bank actually honored it.

But you probably wouldn't be able to auto-deposit that check with the phone on your app, and there is probably a good chance the bank will reject it. Most checks should to be in compliance with ANSI MICR standards. You can read about that here: https://blog.ansi.org/2020/01/micr-specifications-checks-ansi-x9-standards/#gref
